# Generated by Django 4.1.4 on 2022-12-12 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('product_name', models.CharField(db_index=True, max_length=200)),
                ('is_live', models.BooleanField(default=False)),
                ('base_price', models.IntegerField(default=0.0)),
                ('current_price', models.IntegerField(default=0.0)),
                ('description', models.CharField(max_length=500)),
                ('main_photo', models.ImageField(upload_to='photos/main/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/optional/%Y/%m/%d/')),
                ('is_trending', models.BooleanField(default=False)),
                ('on_banner', models.BooleanField(default=False)),
                ('year_published', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 20, 18, 23, 169924))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='home.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('curr_time', models.DateTimeField()),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='home.product')),
            ],
        ),
    ]
